export interface TamplateTypes {
  name: string;
  desc: string;
  category: string;
  icon: string;
  aiPrompt: string;
  slug: string;
  form: FormData[];
}
interface FormData {
  label: string;
  field: string;
  name: string;
  required: boolean;
}

export interface MockInterviewType {
  id: number;
  jsonMockResp: QuestionAnswer[];
  jobPosition: string;
  jobDec: string;
  jobExperience: string;
  createBy: string;
  createdAt: string;
  mockId: string;
}

export interface QuestionAnswer {
  question: string;
  answer: string;
}

export default [
  {
    name: "Blog Title",
    desc: "An AI tool that generates blog titles based on provided blog information.",
    category: "Blog",
    icon: "https://cdn-icons-png.flaticon.com/128/10026/10026257.png",
    aiPrompt:
      "Generate a list of creative blog title ideas based on the following blog niche and outline:",
    slug: "generate-blog-title",
    form: [
      {
        label: "Enter your blog niche",
        field: "input",
        name: "niche",
        required: true,
      },
      {
        label: "Enter blog outline",
        field: "textarea",
        name: "outline",
      },
    ],
  },
  {
    name: "Perfect Email Write",
    desc: "Enhance your email communication with our AI-powered tool that corrects grammar and improves professionalism.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/6125/6125875.png",
    aiPrompt:
      "Write a professional email on given topic. with no gramtical mistake, and Humanatic touch - this email topic",
    slug: "email-rewrite",
    form: [
      {
        label: "Enter your email Topic",
        field: "textarea",
        name: "emailTopic",
        required: true,
      },
    ],
  },
  {
    name: "Blog Title Generator",
    desc: "Generate compelling blog titles tailored to your content with our AI tool.",
    category: "Blog",
    icon: "https://cdn-icons-png.flaticon.com/128/4186/4186534.png",
    aiPrompt:
      "Generate a list of creative blog title ideas based on the following blog niche and outline:",
    slug: "generate-blog-title",
    form: [
      {
        label: "Enter your blog niche",
        field: "input",
        name: "niche",
        required: true,
      },
      {
        label: "Enter blog outline",
        field: "textarea",
        name: "outline",
      },
    ],
  },
  {
    name: "YouTube SEO Title",
    desc: "Optimize your YouTube videos with SEO-friendly titles generated by our AI tool.",
    category: "YouTube",
    icon: "https://cdn-icons-png.flaticon.com/128/402/402075.png",
    aiPrompt:
      "Generate SEO-friendly YouTube titles based on the following video topic and keywords:",
    slug: "youtube-seo-title",
    form: [
      {
        label: "Enter your video topic",
        field: "input",
        name: "topic",
        required: true,
      },
      {
        label: "Enter relevant keywords",
        field: "textarea",
        name: "keywords",
      },
    ],
  },
  {
    name: "YouTube Description Generator",
    desc: "Craft engaging and optimized YouTube descriptions with our AI-powered tool.",
    category: "YouTube",
    icon: "https://cdn-icons-png.flaticon.com/128/2111/2111748.png",
    aiPrompt:
      "Generate an engaging and optimized YouTube description based on the following video topic and details:",
    slug: "youtube-description",
    form: [
      {
        label: "Enter your video topic",
        field: "input",
        name: "topic",
        required: true,
      },
      {
        label: "Enter video details",
        field: "textarea",
        name: "details",
      },
    ],
  },
  {
    name: "Text Improver",
    desc: "Refine your writing with our tool that eliminates errors and redundancies, offering tone analysis and better word choices.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/1686/1686815.png",
    aiPrompt:
      "Improve the following text by eliminating errors and redundancies, and suggest better word choices:",
    slug: "text-improver",
    form: [
      {
        label: "Enter your text",
        field: "textarea",
        name: "text",
        required: true,
      },
    ],
  },
  {
    name: "Instagram Hashtag Generator",
    desc: "Boost your Instagram reach with AI-generated hashtags relevant to your content.",
    category: "Instagram",
    icon: "https://cdn-icons-png.flaticon.com/128/7045/7045432.png",
    aiPrompt:
      "Generate a list of relevant hashtags based on the following Instagram post topic:",
    slug: "instagram-hashtag-generator",
    form: [
      {
        label: "Enter your Instagram post topic",
        field: "input",
        name: "topic",
        required: true,
      },
    ],
  },
  {
    name: "Rewrite Article (Plagiarism-Free)",
    desc: "Use our tool to rewrite articles or blog posts, ensuring they are plagiarism-free and undetectable by AI detectors.",
    category: "Writing",
    icon: "https://cdn-icons-png.flaticon.com/128/3131/3131607.png",
    aiPrompt:
      "Rewrite the following article to make it plagiarism-free and undetectable by AI detectors:",
    slug: "rewrite-article",
    form: [
      {
        label: "Enter your article content",
        field: "textarea",
        name: "articleContent",
        required: true,
      },
    ],
  },
  {
    name: "Code Generator",
    desc: "Generate programming code in any language with our AI tool.",
    category: "Coding",
    icon: "https://cdn-icons-png.flaticon.com/128/2178/2178616.png",
    aiPrompt:
      "Generate the following code snippet in the specified programming language:",
    slug: "code-writer",
    form: [
      {
        label: "Describe the code you need",
        field: "textarea",
        name: "codeDescription",
        required: true,
      },
      {
        label: "Enter the programming language",
        field: "input",
        name: "language",
        required: true,
      },
    ],
  },
  {
    name: "Code Bug Detector",
    desc: "Identify and fix bugs in your code with our tool that offers detailed solutions and alternatives.",
    category: "Coding",
    icon: "https://cdn-icons-png.flaticon.com/128/4426/4426267.png",
    aiPrompt:
      "Analyze the following code snippet and provide detailed solutions for any detected bugs:",
    slug: "code-bug-detector",
    form: [
      {
        label: "Enter your code snippet",
        field: "textarea",
        name: "codeSnippet",
        required: true,
      },
      {
        label: "Describe the issue or error message",
        field: "textarea",
        name: "issueDescription",
      },
    ],
  },

  {
    name: "Commit Message Generator",
    desc: "Generate commit messages using AI-powered conventional commit format generator.",
    category: "Development",
    icon: "https://cdn-icons-png.flaticon.com/128/1041/1041916.png",
    aiPrompt:
      "I want you to act as a commit message generator. I will provide you with information about the task and the prefix for the task code, and I would like you to generate an appropriate commit message using the conventional commit format. Do not write any explanations or other words, just reply with the commit message.",
    slug: "commit-message-generator",
    form: [
      {
        label: "Enter task details",
        field: "textarea",
        name: "task-details",
        required: true,
      },
      {
        label: "Enter prefix for the task code",
        field: "input",
        name: "task-prefix",
        required: true,
      },
    ],
  },
];
